apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor 

metadata:
  name: lan-api
  namespace: monitoring

  labels: 
    release: monitoring

spec:
  namespaceSelector:
    matchNames: 
      - aegis-lab

  selector:
    matchLabels:
      app: lab-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s