import asyncio

from fastapi import FastAPI, Response
from prometheus_client import (
    CONTENT_TYPE_LATEST, 
    Counter,
    Histogram,
    generate_latest,
)
app = FastAPI(title="AEGIS Failure Lab")


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "alive"}


@app.get("/ready")
def ready() -> dict[str, str]:
    return {"status": "ready"}


@app.get("/simulate/error")
def simulate_error(response: Response) -> dict[str, str]:
    SIMULATED_ERRORS.inc()

    response.status_code = 500

    return {
        "status": "error",
        "message": "Simulated internal server error",
    }


@app.get("/simulate/latency")
async def simulate_latency(seconds: int = 3) -> dict[str, str | int]:
    SIMULATED_LATENCY.observe(seconds)
    
    await asyncio.sleep(seconds)

    return {
        "status": "completed",
        "delay_seconds": seconds,
    }

SIMULATED_ERRORS = Counter(
    "aegis_lab_simulated_errors_total",
    "Number of simulated application errors",
)

SIMULATED_LATENCY = Histogram(
    "aegis_lab_simulated_latency_seconds",
    "Latency generated by the simulated endpoint",
)

@app.get("/metrics", include_in_schema=  False)
def metrics() -> Response:
    return Response(
        content=generate_latest(),
        media_type=CONTENT_TYPE_LATEST,
    )
